### ISSUE TITLE
Add function to handle gcbias metric

### ISSUE THREAD

**Issue by nikhil** [mskcc/collect-qc#27]
<img width="567" alt="Screenshot 2023-03-23 at 12 58 32 PM" src="https://user-images.githubusercontent.com/4000697/227977797-89974b09-74cb-432f-950c-9530b4cb51ba.png">

We need to detect the samples for which the line is an outlier from the rest. To do this we can use an R squared threshold function.

For this metric we will plot the values `GC` against `NORMALIZED_COVERAGE`

For this ticket we would add 3 things:
- A R squared threshold function for gcbias metrics *gcbiasmetrics
- Testing for that function
- A line chart of all the samples comparing GC` against `NORMALIZED_COVERAGE`

**Comment by nikhil** [comment]
gcbias:
    function:
      covereage_deviation:
        columns: [GC, NORMALIZED_COVERAGE]
        threshold: some_value

**Comment by nikhil** [comment]
--Correction-- 
We will be using the `rg.md.hstmetrics` file instead of `*gcbiasmetrics`
It will be using the columns '%gc` and `normalized_coverage`

**Comment by nikhil** [comment]
Here is the transformation code
```python
import numpy as np
import pandas as pd


def gcBin(df):
    gc_bin_list = np.arange(.3, .9, .05)
    gc_dict = {}
    nc_dict = {}
    first_bin = gc_bin_list[0]
    for single_bin in gc_bin_list:
        gc_dict[single_bin] = []
        nc_dict[single_bin] = []
    for gc, norm_coverage in zip(df['%gc'], df['normalized_coverage']):
        added_to_bin = False
        for single_bin in gc_bin_list:
            if gc >= single_bin:
                gc_dict[single_bin].append(gc)
                nc_dict[single_bin].append(norm_coverage)
                added_to_bin = True
        if not added_to_bin:
            gc_dict[first_bin].append(gc)
            nc_dict[first_bin].append(norm_coverage)
        gc_data = []
    nc_data = []
    for single_bin in gc_bin_list:
        gc_data.append(np.mean(gc_dict[single_bin]))
        nc_data.append(np.mean(nc_dict[single_bin]))
    gc_bin_data = {"mean_gc": gc_data, "mean_norm_coverage": nc_data}
    gc_df = pd.DataFrame(gc_bin_data)
    return gc_df
```

**Comment by bfarahdel** [comment]
It turns out that the r2 score is not a measure that can clearly distinguish the outlying samples. Instead, the area under the curve can be clearly distinguished between samples. A more detailed description is provided in the pull request.

**Comment by bfarahdel** [comment]
I made a slight modification to the above gcBin function.

```
def gcBin(df):
    gc_bin_list = np.arange(0.3, 0.9, 0.05)
    gc_dict = {}
    nc_dict = {}
    first_bin = gc_bin_list[0]
    for single_bin in gc_bin_list:
        gc_dict[single_bin] = []
        nc_dict[single_bin] = []
    for gc, norm_coverage in zip(df["%gc"], df["normalized_coverage"]):
        added_to_bin = False
        for single_bin in np.flip(gc_bin_list):
            if gc >= single_bin and not added_to_bin:
                gc_dict[single_bin].append(gc)
                nc_dict[single_bin].append(norm_coverage)
                added_to_bin = True
        if not added_to_bin:
            gc_dict[first_bin].append(gc)
            nc_dict[first_bin].append(norm_coverage)
        gc_data = []
    nc_data = []
    for single_bin in gc_bin_list:
        if gc_dict[single_bin] != [] and nc_dict[single_bin] != []:
            gc_data.append(np.mean(gc_dict[single_bin]))
            nc_data.append(np.mean(nc_dict[single_bin]))
    gc_bin_data = {"%gc": gc_data, "normalized_coverage": nc_data}
    gc_df = pd.DataFrame(gc_bin_data)
    return gc_df
```

The `if gc_dict[single_bin] != [] and nc_dict[single_bin] != []` below the `for single_bin in gc_bin_list:` prevents an error when  single_bin does not have values assigned to it. The `np.mean()` function cannot get the mean of an empty array. I also changed the labels in `gc_bin_data`.
